name: learn-github-actions

on: push
env:
      ## Environment variable
  name1: "rajni"
  name2: "rani"
jobs:
 job1:
  runs-on: self-hosted
  steps:
    - name: step1
      run: echo"The name1 is:$name1 $name2"
