name: learn-github-actions

on:
  schedule:
    - cron: '*/1 * * * *'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      #- uses: action/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!